### ISSUE TITLE
confusion with yii required validation

### ISSUE THREAD

**Issue by mgrechanik** [kalyabin/yii2-wysibb#2]
Hi.
There is next workflow which leads to confusion:
1) I have the field with required validation on it
2) I enter text into wisiwig mode of the editor
3) With [[BBCODE]] button I turn into clean textarea to have a look what is there
4) With the same button I turn back to wisiwig and there is a confusion: I have text in the editor but required validator shows JS error.
Here is screenshot:
!(http://www.picshare.ru/view/7194728/)

**Comment by kalyabin** [comment]
This is standard behavior for wysibb.js: plugin does not synchronize the content with input in real-time.

You can use such code to solve a problem:

``` php
$form = ActiveForm::begin([
    ...
]);
print $form->field($model, 'comment')->widget(WysiBBWidget::className());
ActiveForm::end();

/** $this \yii\web\View **/
$this->registerJs("
$(function() {
    $('#" . $form->getId() . "').on('beforeValidate', function(e) {
        $('#" . Html::getInputId($model, 'comment') . "').sync();
        return true;
    });
});
");
```

**Comment by mgrechanik** [comment]
The next code solves the problem:

``` php
Yii::$app->view->registerJs("
      $('#" . $form->getId() . "').on('beforeValidateAttribute', function(e, attribute) {        
        if (attribute.name == 'body') {
          $('#" . Html::getInputId($model, 'body') . "').sync();
        }
        return true;
    });
");
```
